In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### Train Test Split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Feature Scaling

In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test)

In [10]:
X_train_scaled

array([[-0.47281827,  0.15518628, -0.47528501, ..., -0.58777349,
        -0.35794387, -0.35110429],
       [-0.62991393, -0.43597387, -0.64456194, ..., -0.38916166,
        -1.11041768, -1.29770852],
       [ 1.31311137,  0.48698368,  1.25230011, ...,  0.95556525,
        -0.57478578, -0.99365771],
       ...,
       [ 0.43392687,  0.23930393,  0.41191819, ...,  0.48948146,
         1.75869214,  1.22164774],
       [-1.23817732,  0.0266732 , -1.25083747, ..., -1.15594467,
        -0.57316756, -0.26579507],
       [-0.19721184,  2.09923863, -0.25678571, ..., -0.86501817,
        -0.34337986, -0.73554263]])

In [11]:
y_train

301    B
275    B
70     M
77     M
263    M
      ..
194    M
350    B
223    M
548    B
377    B
Name: diagnosis, Length: 455, dtype: object

### Feature Encoding (Label Encoder)

In [12]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [13]:
y_train_encoded

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0])

### Numpy Arrays to PyTorch Tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [54]:
class MySimpleNN():

    def __init__(self, X):
        
        self.weights = torch.rand(X.shape[1],1 , dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred


    def loss_function(self, y_pred, y):
        # clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        # calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1-y_pred)).mean()
        return loss

### Important Parameters

In [55]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [56]:
# Create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculte
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch: {epoch},  Loss: {loss.item()}")

Epoch: 0,  Loss: 3.383005147430539
Epoch: 1,  Loss: 3.2450998145096666
Epoch: 2,  Loss: 3.104367193185241
Epoch: 3,  Loss: 2.9629099006952484
Epoch: 4,  Loss: 2.818223953168533
Epoch: 5,  Loss: 2.669420166191015
Epoch: 6,  Loss: 2.520763346574063
Epoch: 7,  Loss: 2.369365740318396
Epoch: 8,  Loss: 2.2169833903798177
Epoch: 9,  Loss: 2.063251656300037
Epoch: 10,  Loss: 1.910996124991751
Epoch: 11,  Loss: 1.7669007046010994
Epoch: 12,  Loss: 1.630349261250247
Epoch: 13,  Loss: 1.5016916575430699
Epoch: 14,  Loss: 1.3794412134351701
Epoch: 15,  Loss: 1.265234859894172
Epoch: 16,  Loss: 1.166179635814778
Epoch: 17,  Loss: 1.0825830381616786
Epoch: 18,  Loss: 1.0139484937157166
Epoch: 19,  Loss: 0.9589880747069791
Epoch: 20,  Loss: 0.9158254124589092
Epoch: 21,  Loss: 0.8822916374887885
Epoch: 22,  Loss: 0.8562189054430058
Epoch: 23,  Loss: 0.8356756133109325
Epoch: 24,  Loss: 0.8191054455103699

In [58]:
model.weights

tensor([[-0.3813],
        [ 0.4798],
        [ 0.3418],
        [ 0.4108],
        [-0.2740],
        [ 0.3473],
        [ 0.1286],
        [-0.0910],
        [-0.0929],
        [ 0.0105],
        [-0.3749],
        [ 0.5707],
        [ 0.4448],
        [ 0.1176],
        [ 0.6268],
        [-0.3946],
        [ 0.1753],
        [-0.2788],
        [ 0.0958],
        [ 0.1033],
        [-0.0674],
        [-0.2837],
        [ 0.2490],
        [-0.3097],
        [-0.2038],
        [-0.1048],
        [-0.3097],
        [ 0.1489],
        [ 0.2686],
        [ 0.0575]], dtype=torch.float64, requires_grad=True)

In [59]:
model.bias

tensor([-0.1425], dtype=torch.float64, requires_grad=True)

### Evaluation

In [76]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print("Accuracy :", round(accuracy.item(),3))

Accuracy : 0.544