In [28]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [30]:
df.shape

(569, 33)

In [31]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [32]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train Test Split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Feature Scaling

In [34]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test)

In [35]:
X_train_scaled

array([[-1.14100604,  0.51251734, -1.16118549, ..., -1.29766992,
        -0.86855816, -0.14748785],
       [ 0.7446705 ,  2.11174346,  0.71787852, ...,  0.48206629,
        -1.08758463, -0.28086611],
       [-0.35458995,  0.54309078, -0.37681894, ..., -0.96108331,
        -1.15279098, -0.80607758],
       ...,
       [-0.12784954, -1.22311336, -0.10314457, ..., -0.29880237,
         0.32856358, -0.08328919],
       [ 0.87382643, -0.00487935,  0.93031981, ...,  2.20795477,
         0.40212972,  0.4059489 ],
       [-0.46078482, -0.33413178, -0.39972927, ..., -0.56267154,
        -0.52246291,  0.57087305]])

In [36]:
y_train

425    B
566    M
191    B
6      M
67     B
      ..
382    B
184    M
221    B
230    M
431    B
Name: diagnosis, Length: 455, dtype: object

### Feature Encoding (Label Encoder)

In [37]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [38]:
y_train_encoded

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0])

### Numpy Arrays to PyTorch Tensors

In [57]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

C:\Users\DELL\AppData\Local\Temp\ipykernel_16104\2138333846.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
C:\Users\DELL\AppData\Local\Temp\ipykernel_16104\2138333846.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)
C:\Users\DELL\AppData\Local\Temp\ipykernel_16104\2138333846.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
C:\Users\DELL\AppData\Local\Temp\ipykernel_16104\2138333846.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [48]:
X_train_tensor.shape

torch.Size([455, 30])

In [49]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [66]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameters

In [67]:
learning_rate = 0.1
epochs = 25

In [68]:
# define loss function
loss_function = nn.BCELoss()

### Training Pipeline

In [69]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
    
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculte
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()
    
    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f"Epoch: {epoch},  Loss: {loss.item()}")

Epoch: 0,  Loss: 0.6790637969970703
Epoch: 1,  Loss: 0.5356864333152771
Epoch: 2,  Loss: 0.4545116722583771
Epoch: 3,  Loss: 0.4016668498516083
Epoch: 4,  Loss: 0.364004522562027
Epoch: 5,  Loss: 0.33549264073371887
Epoch: 6,  Loss: 0.3129647970199585
Epoch: 7,  Loss: 0.2945895791053772
Epoch: 8,  Loss: 0.279229074716568
Epoch: 9,  Loss: 0.26613640785217285
Epoch: 10,  Loss: 0.25479942560195923
Epoch: 11,  Loss: 0.24485433101654053
Epoch: 12,  Loss: 0.23603501915931702
Epoch: 13,  Loss: 0.22814185917377472
Epoch: 14,  Loss: 0.22102195024490356
Epoch: 15,  Loss: 0.2145560085773468
Epoch: 16,  Loss: 0.2086494266986847
Epoch: 17,  Loss: 0.2032260149717331
Epoch: 18,  Loss: 0.19822369515895844
Epoch: 19,  Loss: 0.19359122216701508
Epoch: 20,  Loss: 0.18928596377372742
Epoch: 21,  Loss: 0.1852719485759735
Epoch: 22,  Loss: 0.1815185844898224
Epoch: 23,  Loss: 0.17799977958202362
Epoch: 24,  Loss: 0.17469289898872375

In [62]:
model.linear.weight

Parameter containing:
tensor([[ 0.3173,  0.2284,  0.1788,  0.2822,  0.0520,  0.2388,  0.3443,  0.3000,
          0.0579, -0.0346,  0.1831,  0.1165,  0.0609,  0.2968,  0.0150, -0.1121,
          0.1534, -0.0868, -0.0973, -0.2259,  0.1105,  0.1676,  0.1440,  0.3984,
          0.0050,  0.2460,  0.1818,  0.2459,  0.1217,  0.1372]],
       requires_grad=True)

In [63]:
model.linear.bias

Parameter containing:
tensor([-0.1731], requires_grad=True)

### Evaluation

In [64]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print("Accuracy :", round(accuracy.item(),3))

Accuracy : 0.501