In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Feature Scaling

In [7]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled = scaler.transform(X_test)

In [8]:
X_train_scaled

array([[-0.28718211,  0.61346896, -0.28595255, ...,  0.68099226,
         1.28217307,  0.68516959],
       [ 0.18014606,  1.12702466,  0.21836482, ...,  0.69173816,
         0.6770672 ,  0.28533144],
       [-0.57164274, -1.44075386, -0.55284505, ..., -0.5291504 ,
         0.91780825,  0.47196028],
       ...,
       [ 1.82305133,  0.60623578,  1.75068137, ...,  0.92354273,
        -0.48109241, -0.9452878 ],
       [-0.82417411,  1.88409739, -0.86099222, ..., -1.46619349,
        -0.09070153, -0.74621704],
       [-0.85320071,  3.50674053, -0.90182593, ..., -1.32511509,
         0.01014945, -0.62179782]])

In [9]:
y_train

44     M
65     M
130    B
500    B
560    B
      ..
183    B
47     M
365    M
231    B
232    B
Name: diagnosis, Length: 455, dtype: object

### Feature Encoding (Label Encoder)

In [10]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [11]:
y_train_encoded

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

### Numpy Arrays to PyTorch Tensors

In [12]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train_encoded, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_encoded, dtype=torch.float32)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=True)

### Defining the model

In [18]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameters

In [19]:
learning_rate = 0.1
epochs = 25

In [21]:
# Create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

### Training Pipeline

In [22]:
# define loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:
        
        # forward pass
        y_pred = model(batch_features)

        # loss calculte
        loss = loss_function(y_pred, batch_labels.view(-1,1))

        # clear gradients
        optimizer.zero_grad()
        
        # backward pass
        loss.backward()

        # parameters update
        optimizer.step()

    # print loss in each epoch
    print(f"Epoch: {epoch+1},  Loss: {loss.item()}")

Epoch: 1,  Loss: 0.15109889209270477
Epoch: 2,  Loss: 0.09574013948440552
Epoch: 3,  Loss: 0.12124710530042648
Epoch: 4,  Loss: 0.09873144328594208
Epoch: 5,  Loss: 0.09529571980237961
Epoch: 6,  Loss: 0.0613478384912014
Epoch: 7,  Loss: 0.09470158070325851
Epoch: 8,  Loss: 0.05738496780395508
Epoch: 9,  Loss: 0.16236035525798798
Epoch: 10,  Loss: 0.17112144827842712
Epoch: 11,  Loss: 0.03176012635231018
Epoch: 12,  Loss: 0.09586657583713531
Epoch: 13,  Loss: 0.02936822734773159
Epoch: 14,  Loss: 0.02553844079375267
Epoch: 15,  Loss: 0.10557849705219269
Epoch: 16,  Loss: 0.13388891518115997
Epoch: 17,  Loss: 0.016017097979784012
Epoch: 18,  Loss: 0.04168108478188515
Epoch: 19,  Loss: 0.014821955002844334
Epoch: 20,  Loss: 0.20122666656970978
Epoch: 21,  Loss: 0.04071781784296036
Epoch: 22,  Loss: 0.011222044937312603
Epoch: 23,  Loss: 0.04910700395703316
Epoch: 24,  Loss: 0.06460970640182495
Epoch: 25,  Loss: 0.018459469079971313

In [23]:
model.linear.weight

Parameter containing:
tensor([[ 0.6256,  0.5328,  0.4528,  0.6310,  0.2527,  0.1111,  0.2560,  0.4221,
          0.1942, -0.3034,  0.5786, -0.0597,  0.6249,  0.3243,  0.1172, -0.2727,
         -0.0475, -0.0273, -0.3051, -0.2863,  0.6247,  0.7347,  0.5576,  0.7543,
          0.5694,  0.1566,  0.5655,  0.7267,  0.4584,  0.0741]],
       requires_grad=True)

In [24]:
model.linear.bias

Parameter containing:
tensor([-0.3992], requires_grad=True)

### Evaluation

In [25]:
# Model Evaluation using test_loader
model.eval()    # set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # forward pass
        y_pred = model.forward(batch_features)
        y_pred = (y_pred > 0.5).float()   # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch 
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

Accuracy: 0.9705